apps/utilities/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('repository_detail/<int:repository_id>/', views.repository_detail, name='repository_detail'),
    
    path('history/', views.history, name="history"),
    path('add_repository/<int:folder_id>/', views.add_repository, name='add_repository_with_folder'),
    path('search_repository/', views.search_repository, name='search_repository'),
    path('save_repository/', views.save_repository, name='save_repository'),
    path('delete_repository/<int:repository_id>/', views.delete_repository, name='delete_repository'),
    path('delete_folder/<int:folder_id>/', views.delete_folder, name='delete_folder'),
]

gittrackr/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("__reload__", include("django_browser_reload.urls")),
    path('', views.index, name="landingPage"),
    path('logged/', views.indexLogged, name="loggedHomepage"),
    path('accounts/', include('apps.accounts.urls')),
    path('comparison/', include('apps.comparison.urls')),
    path('utilities/', include('apps.utilities.urls')),

    path('create_folder/', views.create_folder, name='create_folder'),
]

apps/utilities/models.py
from django.db import models

#Create your models in here.

master/models.py
from django.db import models
from django.contrib.auth.models import User

class Folders(models.Model):
    FolderID = models.AutoField(primary_key=True)
    Folder_Name = models.CharField(max_length=255, unique=True)
    Created_At = models.DateTimeField(auto_now_add=True)
    UserID = models.ForeignKey(User, on_delete=models.CASCADE)

class Repository(models.Model):
    RepositoryID = models.AutoField(primary_key=True)
    Repository_Name = models.CharField(max_length=255, unique=True)
    Owner = models.CharField(max_length=255, null=True)
    Url = models.TextField()
    Folder_ID = models.ForeignKey(Folders, on_delete=models.CASCADE, null=True, blank=True)

class History(models.Model):
    HistoryID = models.AutoField(primary_key=True)
    Timestap = models.DateTimeField()
    UserID = models.ForeignKey(User, on_delete=models.CASCADE)
    FolderID = models.ForeignKey(Folders, on_delete=models.CASCADE)

apps/utilities/forms.py
# forms.py
from django import forms

class AddRepositoryForm(forms.Form):
    repository_name = forms.CharField(
        label='',
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'w-96 mx-4 border-2 rounded-xl m-4', 'placeholder' : 'ex. DjangoEcommerce'},)
        )

apps/utilities/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib import messages
from django.http import JsonResponse
from datetime import datetime, timedelta
from github import Github

from .forms import AddRepositoryForm
from master.models import Repository, Folders

import requests
import json

@login_required
def repository_detail(request, repository_id):
    repo = Repository.objects.get(RepositoryID=repository_id)

    g = Github(settings.GITHUB_TOKEN)

    github_repo = g.get_repo(f"{repo.Owner}/{repo.Repository_Name}")

    languages = github_repo.get_languages()
    total_bytes = sum(languages.values())
    formatted_languages = {lang: f"{(bytes / total_bytes) * 100:.1f}%" for lang, bytes in languages.items()}

    details = {
        'Repository_Name': repo.Repository_Name,
        'Owner_Name': repo.Owner,
        'About': github_repo.description,
        'Languages': formatted_languages,
        'File_Size': github_repo.size,
        'Date_Created': github_repo.created_at,
        'Topics': github_repo.get_topics(),
        'Branch': github_repo.default_branch,
        'Contributors': [contributor.login for contributor in github_repo.get_contributors()],
        'Stars': github_repo.stargazers_count,
        'CountCommit': json.dumps(get_github_data(github_repo)),
        'CountPullreq': json.dumps(count_pull_requests(github_repo)),
    }

    return render(request, 'utilities/repository_detail.html', {'details': details, 'repository_id': repository_id})


def get_github_data(repo):
    commit_count_data = {}

    for commit in repo.get_commits():
        timestamp = commit.commit.author.date.timestamp()
        commit_date = datetime.fromtimestamp(timestamp)
        month_year = commit_date.strftime('%Y-%m')
        contributor = commit.commit.author.name

        if month_year not in commit_count_data:
            commit_count_data[month_year] = {'total': 0, 'contributors': {}}

        commit_count_data[month_year]['total'] += 1

        if contributor not in commit_count_data[month_year]['contributors']:
            commit_count_data[month_year]['contributors'][contributor] = 1
        else:
            commit_count_data[month_year]['contributors'][contributor] += 1
        
    return commit_count_data

def count_pull_requests(repo):
    pull_requests = repo.get_pulls(state='all')
    pull_request_count_data = {}

    for pull_request in pull_requests:
        timestamp = pull_request.created_at.timestamp()
        pull_request_date = datetime.fromtimestamp(timestamp)
        month_year = pull_request_date.strftime('%Y-%m')
        contributor = pull_request.user.login

        if month_year not in pull_request_count_data:
            pull_request_count_data[month_year] = {'total': 0, 'contributors': {}}
        pull_request_count_data[month_year]['total'] += 1

        if contributor not in pull_request_count_data[month_year]['contributors']:
            pull_request_count_data[month_year]['contributors'][contributor] = 1
        else:
            pull_request_count_data[month_year]['contributors'][contributor] += 1

    return pull_request_count_data

@login_required
def history(request):
    folders = Folders.objects.filter(UserID=request.user)
    return render(request, 'utilities/history.html', {'folders': folders})

@login_required
def add_repository(request, folder_id=None):
    if folder_id is not None:
        request.session['current_folder_id'] = folder_id

    folder_id = request.session.get('current_folder_id')
    folder = Folders.objects.get(FolderID=folder_id)

    form = AddRepositoryForm()
    folders = Folders.objects.all()
    return render(request, 'utilities/add_repository.html', {'form': form, 'folder': folder, 'folders': folders})

@login_required
def search_repository(request):
    if request.method == 'POST':
        form = AddRepositoryForm(request.POST)
        if form.is_valid():
            full_repository_name = form.cleaned_data['repository_name']

            headers = {'Authorization': f'token {settings.GITHUB_TOKEN}'}
            url = f'https://api.github.com/search/repositories?q={full_repository_name}'

            response = requests.get(url, headers=headers)

            if response.status_code == 200:
                form = AddRepositoryForm()
                data = response.json()
                repositories = data.get('items', [])

                for repository in repositories:
                    repository['repository_owner'], repository['repository_name'] = repository['full_name'].split('/')

                folders = Folders.objects.all()

                folder_id = request.session.get('current_folder_id')
                folder = Folders.objects.get(FolderID=folder_id)

                return render(request, 'utilities/add_repository.html', {'form': form, 'repositories': repositories, 'folders': folders, 'folder': folder})
            else:
                print(f'Error {response.status_code}: {response.text}')

    return redirect('add_repository')


@login_required
def save_repository(request):
    if request.method == 'POST':
        repository_name = request.POST.get('repository_name')
        owner = request.POST.get('repository_owner')
        repository_url = request.POST.get('repository_url')
        folder_id = request.session.get('current_folder_id')

        if Repository.objects.filter(Repository_Name=repository_name, Folder_ID_id=folder_id, Url=repository_url).exists():
            messages.error(request, 'Repositori ini sudah ada di folder ini.')
            return redirect('add_repository_with_folder', folder_id=folder_id)

        repository = Repository(Owner=owner, Repository_Name=repository_name, Url=repository_url, Folder_ID_id=folder_id)
        repository.save()

    return redirect('add_repository_with_folder', folder_id=folder_id)


def five_repository(request):
    saved_repositories = Repository.objects.all()[:5]
    return render(request, 'add_repository.html', {'saved_repositories': saved_repositories})

templates/utilities/add_repository.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Repository</title>
    {% tailwind_css %}
</head>

<body class="overflow-x-hidden">

    {% block section %}
    {% include "component/navbar_logged.html" %}
    {% endblock %}

    <div class="relative flex flex-row z-10 py-40 justify-center">

    <!-- Content Start -->
    <div class="grid lg:grid-cols-2 gap-10 lg:mx-28 flex flex-row z-10 py-40 justify-center">
        <div class="bg-white lg:mx-16 mx-8 border-2 rounded-xl h-fit">
            <div class="border-b-2 px-4 py-4">
                <h1 class="text-black text-xl font-bold">{{ folder.Folder_Name }}'s Folder</h1>
            </div>

            <div class="flex items-center px-4 py-4">
                <!-- SVG Icon -->
                <svg width="44" height="53" viewBox="0 0 54 63" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M9.66992 49.8131V13.149C9.66992 11.7599 10.1364 10.4276 10.9669 9.44535C11.7973 8.46309 12.9236 7.91125 14.098 7.91125H43.7658C44.1181 7.91125 44.456 8.0768 44.7051 8.37148C44.9542 8.66616 45.0942 9.06583 45.0942 9.48257V43.8264"
                        stroke="black" stroke-width="1.5" stroke-linecap="round" />
                    <path d="M34.0242 44.5753V57.6696L39.5592 53.4795L45.0942 57.6696V44.5753" stroke="black"
                        stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                    <path d="M14.0979 44.5753H45.0941" stroke="black" stroke-width="1.5" stroke-linecap="round" />
                    <path
                        d="M14.098 44.5753C12.9236 44.5753 11.7973 45.1271 10.9669 46.1094C10.1364 47.0917 9.66992 48.4239 9.66992 49.813C9.66992 51.2022 10.1364 52.5344 10.9669 53.5167C11.7973 54.4989 12.9236 55.0508 14.098 55.0508H26.275"
                        stroke="black" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                </svg>
                <!-- Repository Title -->
                <p class="px-2 text-center text-black text-xl font-semibold">Add repository</p>
            </div>
            <!-- Input Repository -->
            <div class="py-4 px-2 w-full">
                <form class="grid" method="post" action="{% url 'search_repository' %}">
                    {% csrf_token %}
                    {{ form.repository_name }}
                    <input type="submit" value="Submit" class="w-fit m-4 py-2 px-4 border border-black rounded-xl hover:bg-gray-100 hover:border-gray-500">
                </form>
            </div>

            <!-- Maximum 5 Repositories Display -->
            <div class="border-t-2 my-4 px-4 justify-center items-center">
                <p class="my-4 mx-2 text-black text-xs font-extralight font-['Montserrat']">maks 5 repository</p>
                <div id="" class="grid gap-2 md:grid-cols-3 grid-cols-2 col-auto row-auto auto-cols-max auto-rows-max">
                    <!-- for anjing babii -->
                    <div class="w-fit shadow-xl rounded-lg flex justify-between items-center text-xs">
                        <p>{{ Repository.Repository_Name }}</p>
                        <p class="lg:mx-4 my-2 mx-2">TEST Satrya</p>
                        <svg class="mx-4 my-2" width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M11.5563 1.75736L7.31371 6L11.5563 10.2426L10.1421 11.6569L5.89949 7.41421L1.65685 11.6569L0.242641 10.2426L4.48528 6L0.242641 1.75736L1.65685 0.343146L5.89949 4.58579L10.1421 0.343146L11.5563 1.75736Z" fill="black"/>
                        </svg>
                    </div>
                    <!-- endfor ajg babii -->
                </div>
            </div>

            <!-- Button Actions -->
            <div class="flex px-8 py-4 border-t-2 justify-between">
                <button type="button" class="bg-white border py-2 px-6 rounded-2xl border-black">
                    <p class="text-center text-black text-lg font-semibold">Cancel</p>
                </button>
                <button type="button" class="bg-black border py-2 px-4 rounded-2xl border-black">
                    <a href="{% url 'compare_repositories' folder.FolderID %}"
                        class="text-center text-white text-lg font-semibold">Compare</a>
                </button>
            </div>
        </div>

        <!-- Repository List -->
        <div>
            <ul class="grid grid-cols-2 mx-10">
                {% for repository in repositories %}
                <li class="py-2 mx-2">
                    <div class="bg-white shadow-lg rounded-lg p-2">
                        <strong class="text-md py-1 px-2">{{ repository.repository_name }}</strong><br>
                        <strong class="text-xs py-1 px-2">Owner:</strong><br>
                        <strong class="text-xs py-1 px-2">{{ repository.repository_owner }}</strong>
                        <form method="post" action="{% url 'save_repository' %}">
                            {% csrf_token %}
                            <input type="hidden" name="repository_name" value="{{ repository.repository_name }}">
                            <input type="hidden" name="repository_owner" value="{{ repository.repository_owner }}">
                            <input type="hidden" name="repository_url" value="{{ repository.html_url }}">
                            <button type="submit"
                                class="my-2 py-1 px-2 border text-xs border-black rounded-lg hover:bg-gray-100 hover:border-gray-500 add-to-folder-button">Add
                                to My Folder</button>
                        </form>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>

        <!-- Display Messages -->
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

    </div>

    
    <!-- Content End -->
    <script>
        console.log("Saved Repositories:", {{ save_repositories }});

        document.addEventListener("DOMContentLoaded", function () {
            const dropdownButton = document.querySelector(".group");
            const dropdownMenu = document.querySelector(".absolute");

            dropdownButton.addEventListener("click", function () {
                dropdownMenu.classList.toggle("hidden");
            });
        });

        var containerCount = 0;
        var permanentValues = [];

        function clearInputValue() {
            document.getElementById('txt').value = '';
        }

        function getValue() {
            var input = document.getElementById('txt').value;
            var svg = document.getElementById('mySvg');
            var result = document.getElementById('result');
            result.textContent = input;

            if (input.trim() === "") {
                svg.style.display = "none";
            } else {
                svg.style.display = "block";
            }
        }

        document.getElementById('clickableDiv').addEventListener('click', function () {
            showPermanentValue();
        });

        function deletePermanentValue(valueElement, containerId) {
            valueElement.parentNode.remove();
            var index = permanentValues.indexOf(valueElement.textContent);
            if (index > -1) {
                permanentValues.splice(index, 1);
            }
            containerCount--;

            if (containerCount < 5) {
                document.getElementById('clickableDiv').addEventListener('click', showPermanentValue);
            }
        }

        function showPermanentValue() {
            if (containerCount < 5) {
                var result = document.getElementById('result');
                var permanentValue = document.createElement('p');
                permanentValue.textContent = result.textContent;

                containerCount++;
                var permanentValuesContainer = document.createElement('div');
                permanentValuesContainer.id = "permanentValuesContainer" + containerCount;
                permanentValuesContainer.className = "flex py-2 px-4 bg-white shadow-xl rounded-lg w-fit items-center justify-between";

                var deleteButton = document.createElement('div');
                deleteButton.innerHTML = `<svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M11.5563 1.75736L7.31371 6L11.5563 10.2426L10.1421 11.6569L5.89949 7.41421L1.65685 11.6569L0.242641 10.2426L4.48528 6L0.242641 1.75736L1.65685 0.343146L5.89949 4.58579L10.1421 0.343146L11.5563 1.75736Z" fill="black"/>
            </svg>`;
                deleteButton.className = "your-class-name"; // Ganti your-class-name dengan nama kelas Anda
                deleteButton.addEventListener('click', function () {
                    deletePermanentValue(permanentValue, permanentValuesContainer.id);
                });

                // Menambahkan style untuk SVG
                permanentValuesContainer.style.width = "190px";
                deleteButton.style.display = "flex";
                deleteButton.style.alignItems = "start";
                deleteButton.style.justifyContent = "space-between";

                permanentValuesContainer.appendChild(permanentValue);
                permanentValuesContainer.appendChild(deleteButton);
                document.getElementById('permanentValuesContainer').appendChild(permanentValuesContainer);
                permanentValues.push(permanentValue.textContent);

                if (containerCount === 5) {
                    document.getElementById('clickableDiv').removeEventListener('click', showPermanentValue);
                }
            }
            clearInputValue();

            // Setelah menyimpan repository, tangani respons JSON untuk memperbarui tampilan
            $.ajax({
                url: '{% url "save_repository" %}',  // Use the correct URL for saving repository
                method: 'POST',
                data: {'repository_name': input},
                dataType: 'json',
                success: function (data) {
                    // Update tampilan dengan daftar repository yang akan disimpan
                    updatePermanentValues(data.saved_repositories);
                },
                error: function () {
                    console.log('Gagal menyimpan repository.');
                }
            });
            clearInputValue();
        }

        function updatePermanentValues(savedRepositories) {
            var permanentValuesContainer = $('#permanentValuesContainer');
            permanentValuesContainer.empty();  // Hapus semua elemen sebelumnya

            for (const savedRepository of savedRepositories) {
                const permanentValue = $('<p>').text(savedRepository);

                const deleteButton = $('<div>').html(`<svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M11.5563 1.75736L7.31371 6L11.5563 10.2426L10.1421 11.6569L5.89949 7.41421L1.65685 11.6569L0.242641 10.2426L4.48528 6L0.242641 1.75736L1.65685 0.343146L5.89949 4.58579L10.1421 0.343146L11.5563 1.75736Z" fill="black"/>
                </svg>`);
                deleteButton.on('click', function () {
                    deletePermanentValue(permanentValue, permanentValuesContainer.attr('id'));
                });

                // Adding styles for SVG
                permanentValuesContainer.css('width', '190px');
                deleteButton.css('display', 'flex');
                deleteButton.css('align-items', 'start');
                deleteButton.css('justify-content', 'space-between');

                permanentValuesContainer.append(permanentValue);
                permanentValuesContainer.append(deleteButton);
            }
        }
    </script>
</body>
</html>

templates/utilities/history.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>History</title>
    {% tailwind_css %}
</head>

<body>
    <!-- Navbar Start -->
    {% block section %}
    {% include "component/navbar_logged.html" %}
    {% endblock %}
    <!-- Navbar End -->

    <!-- Content Start -->
    <div class="relative flex pt-36 sm:pt-40 justify-between sm:px-32 px-4 items-center">
        <a href="" class="w-fit flex rounded-lg shadow-xl bg-white px-4 py-2 items-center">
            <button type="button" class="text-xs">Add New Folder</button>
            <svg class="mx-2" width="15" height="14" viewBox="0 0 15 14" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M14.0352 7.99805H8.03516V13.998H6.03516V7.99805H0.0351562V5.99805H6.03516V-0.00195312H8.03516V5.99805H14.0352V7.99805Z" fill="black"/>
                </svg>
        </a>
        <div class="flex items-center border border-gray-300 rounded-lg px-2">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M15.5 14H14.71L14.43 13.73C15.4439 12.554 16.0011 11.0527 16 9.5C16 8.21442 15.6188 6.95772 14.9046 5.8888C14.1903 4.81988 13.1752 3.98676 11.9874 3.49479C10.7997 3.00282 9.49279 2.87409 8.23192 3.1249C6.97104 3.3757 5.81285 3.99477 4.90381 4.90381C3.99477 5.81285 3.3757 6.97104 3.1249 8.23192C2.87409 9.49279 3.00282 10.7997 3.49479 11.9874C3.98676 13.1752 4.81988 14.1903 5.8888 14.9046C6.95772 15.6188 8.21442 16 9.5 16C11.11 16 12.59 15.41 13.73 14.43L14 14.71V15.5L19 20.49L20.49 19L15.5 14ZM9.5 14C7.01 14 5 11.99 5 9.5C5 7.01 7.01 5 9.5 5C11.99 5 14 7.01 14 9.5C14 11.99 11.99 14 9.5 14Z" fill="#545454"/>
                </svg>
            <input type="text" class="w-fit lg:w-96 text-xs sm:text-base border-none focus:outline-none no-underline focus:border-none" placeholder="Search..">
        </div>
    </div>
    <div class="py-4 sm:px-28 px-4">
        <h1 class="text-black text-2xl font-medium py-2 ml-2">
            Recently
        </h1>
        <div class="grid lg:grid-cols-4 grid-cols-2 gap-2 xl:gap-10">
            {% for folder in folders %}
            <div class="bg-sky-100 px-3 sm:px-4 py-2 w-fit rounded-xl shadow-lg">
                <a href="{% url 'add_repository_with_folder' folder_id=folder.FolderID %}">
                    <div class="flex flex-col justify-between">
                        <div class="flex items-center">
                            <h1 class="text-black text-md sm:text-base lg:text-xl font-medium">Repo name: <b>{{ folder.Folder_Name }}</b> </h1>
                        </div>
                        <div class="flex items-center text-xs sm:text-base lg:text-lg">
                            <p>Created at: <br> <b>{{ folder.Created_At }}</b> </p>
                        </div>
                    </div>
                    <div class="">
                        <p class="text-black text-md sm:text-base lg:text-xl font-bold leading-9 py-2">
                            Repositories List:
                        </p>
                        <ul class="list-disc text-black text-xs font-normal px-4 sm:px-5">
                            {% for repository in folder.repository_set.all %}
                            <li>
                                {{ repository.Owner }} / {{ repository.Repository_Name }}
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

        <script>
            document.addEventListener("DOMContentLoaded", function () {
                const dropdownButton = document.querySelector(".group");
                const dropdownMenu = document.querySelector(".absolute");

                dropdownButton.addEventListener("click", function () {
                    dropdownMenu.classList.toggle("hidden");
                });
            });
        </script>
</body>

</html>